### PR TITLE
Add feature importance description for counterfactual local importance

### PR DESCRIPTION
**Pull request by gaugup**
Add the "Percentage of counterfactuals that varied the feature" to local importance for counterfactual point.

## Description

image

## Areas changed

npm packages changed:

- [ ] responsibleai/causality
- [ ] responsibleai/core-ui
- [x] responsibleai/counterfactuals
- [ ] responsibleai/dataset-explorer
- [ ] responsibleai/fairness
- [ ] responsibleai/interpret
- [ ] responsibleai/localization
- [ ] responsibleai/mlchartlib
- [ ] responsibleai/model-assessment

Python packages changed:

- [ ] raiwidgets
- [ ] responsibleai
- [ ] erroranalysis
- [ ] rai_core_flask

## Tests

- [ ] No new tests required.
- [ ] New tests for the added feature are part of this PR.
- [x] I validated the changes manually.

## Documentation:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by imatiach-msft — APPROVED** [review]

**Review by vinuthakaranth — APPROVED** [review]

**Review by zhb000 — APPROVED** [review]
This title string could be localized

**Comment by imatiach-msft** [comment]
@zhb000 oh good point it should be localized

**Comment by gaugup** [comment]
> This title string could be localized

@zhb000 how do I add the localization code for this change?

**Comment by gaugup** [comment]
> > This title string could be localized
> 
> @zhb000 how do I add the localization code for this change?

@zhb000, I added the string in the localization json file.

**Pull request merged**
