### PR TITLE
Move ModelTask to raiutils and create forecasting utils

### PR DESCRIPTION
**Pull request by romanlutz**
## Description

The `ModelTask` enum is a central to most of our packages, so moving it to raiutils is overdue. It turns out we also had multiple definitions (in responsibleai and erroranalysis) which this PR unifies (by taking the erroranalysis one).

The PR also adds `Forecasting`, `is_forecaster` and `is_quantile_forecaster` as utilities that will be needed for forecasting support shortly.

## Checklist

- [ ] I have added screenshots above for all UI changes.
- [ ] I have added e2e tests for all UI changes.
- [ ] Documentation was updated if it was needed.

### CODE REVIEW

**Review by gaugup — COMMENTED** [review]
could you add unit tests for this change?

**Comment by romanlutz** [comment]
> could you add unit tests for this change?

Done!

**Comment by gaugup** [comment]
> > could you add unit tests for this change?
> 
> Done!

Sorry, don't see the tests in the PR. Am I missing something?

**Comment by romanlutz** [comment]
> Sorry, don't see the tests in the PR. Am I missing something?

`git push` failed due to diverging branches at first. I should have read the message instead of assuming it succeeded 🙂 You should be able to see the test updates now.

**Review by gaugup — APPROVED** [review]

**Pull request merged**
