### PR TITLE
fix outdated example link in Error Analysis README

### PR DESCRIPTION
**Pull request by JarvisG495**
## Description
Update the link to the housing price prediction example notebook in Error Analysis README to fix 404.

## Checklist

- [ ] I have added screenshots above for all UI changes.
- [ ] I have added e2e tests for all UI changes.
- [ ] Documentation was updated if it was needed.

### CODE REVIEW

**Comment by JarvisG495** [comment]
btw, I'm wondering if other example links in this README should be updated in this PR as well -- it seems they are also outdated but they can be automatically redirected to the correct files..

**Comment by romanlutz** [comment]
> btw, I'm wondering if other example links in this README should be updated in this PR as well -- it seems they are also outdated but they can be automatically redirected to the correct files..

Hi @JarvisG495 thanks for fixing this! Which other links are broken? If you happen to be able to update the others, too, you can feel free to add it in this PR. We always want them to be up-to-date, but sadly sometimes we miss a few. Thanks for helping us keep it in shape 🙂

**Review by imatiach-msft — APPROVED** [review]
LGTM!

**Comment by JarvisG495** [comment]
> > btw, I'm wondering if other example links in this README should be updated in this PR as well -- it seems they are also outdated but they can be automatically redirected to the correct files..
> 
> Hi @JarvisG495 thanks for fixing this! Which other links are broken? If you happen to be able to update the others, too, you can feel free to add it in this PR. We always want them to be up-to-date, but sadly sometimes we miss a few. Thanks for helping us keep it in shape 🙂

Actually they're not broken -- I just found other links were not very "consistent" when I was updating the link to the housing price prediction example notebook: they are '.../microsoft/**responsible-ai-widgets**/blob/**master**/notebooks/.../\*.ipynb' instead of '.../microsoft/**responsible-ai-toolbox**/blob/**main**/notebooks/.../\*.ipynb'. Since they could be automatically redirected to this repo and main branch, I was not sure if they needed to be updated so I didn't modify them in this PR.

Screen Shot 2023-02-13 at 4 29 54 PM

Screen Shot 2023-02-13 at 4 26 08 PM

**Comment by romanlutz** [comment]
> > > btw, I'm wondering if other example links in this README should be updated in this PR as well -- it seems they are also outdated but they can be automatically redirected to the correct files..
> 
> > 
> 
> > Hi @JarvisG495 thanks for fixing this! Which other links are broken? If you happen to be able to update the others, too, you can feel free to add it in this PR. We always want them to be up-to-date, but sadly sometimes we miss a few. Thanks for helping us keep it in shape 🙂
> 
> 
> 
> Actually they're not broken -- I just found other links were not very "consistent" when I was updating the link to the housing price prediction example notebook: they are '.../microsoft/**responsible-ai-widgets**/blob/**master**/notebooks/.../\*.ipynb' instead of '.../microsoft/**responsible-ai-toolbox**/blob/**main**/notebooks/.../\*.ipynb'. Since they could be automatically redirected to this repo and main branch, I was not sure if they needed to be updated so I didn't modify them in this PR.
> 
> 
> 
> Screen Shot 2023-02-13 at 4 29 54 PM
> 
> 
> 
> Screen Shot 2023-02-13 at 4 26 08 PM
> 
> 

Ah yes! "master" was replaced by "main" but the auto-redirects work. Still, it would be best to replace it. @JarvisG495 feel free to send a PR if you have time 🙂

**Comment by JarvisG495** [comment]
> 
> Ah yes! "master" was replaced by "main" but the auto-redirects work. Still, it would be best to replace it. @JarvisG495 feel free to send a PR if you have time 🙂

ok, I will send another PR to update them soon 😃

**Pull request merged**
