### PR TITLE
default categorical feature to array

### PR DESCRIPTION
**Pull request by xuke444**
Signed-off-by: Ke xu <xuke@microsoft.com>

### CODE REVIEW

**Comment by gaugup** [comment]
I remember we had a discussion around keeping it as None if not specified. Why is this being changed back?

**Comment by imatiach-msft** [comment]
+1 confused why this is being changed back

**Comment by xuke444** [comment]
it breaks ui and there will be a lot places to change on ui instead of fix in sdk.

**Review by imatiach-msft — APPROVED** [review]

**Comment by imatiach-msft** [comment]
@xuke444 I'm actually seeing this issue now with the notebook I'm adding in this PR:
https://github.com/microsoft/responsible-ai-toolbox/pull/1105
the UX just seems to break because no categorical features are specified, which is really bad.  I think this should be merged ASAP, otherwise non-categorical scenarios are broken.

**Pull request merged**
