### PR TITLE
Adding Object Detection Fridge Data

### PR DESCRIPTION
**Pull request by natalie-isak**
This PR adds support for sample data for the object detection scenario. 
Screenshot 2023-03-08 144056

### CODE REVIEW

**Review by imatiach-msft — APPROVED** [review]

**Comment by natalie-isak** [comment]
@imatiach-msft I looked into it and I think it was because the dataset was too large. Looks like build is passing now!

**Review by RubyZ10 — APPROVED** [review]

**Review by imatiach-msft — APPROVED** [review]

**Comment by imatiach-msft** [comment]
awesome! please merge when you are ready.

**Comment by natalie-isak** [comment]
@imatiach-msft I believe I am not authorized to merge. Would you mind merging the PR? Thanks so much!

**Comment by imatiach-msft** [comment]
@natalie-isak done, merged!

**Pull request merged**
