### PR TITLE
add flake8-bugbear for better python code contructs

### PR DESCRIPTION
**Pull request by gaugup**

### CODE REVIEW

**Review by imatiach-msft — APPROVED** [review]
Since the build is green, and I don't see any other changes, does this mean our code is already perfect?

**Comment by imatiach-msft** [comment]
I guess it just writes warnings but doesn't trigger failures?

**Comment by gaugup** [comment]
> Since the build is green, and I don't see any other changes, does this mean our code is already perfect?

I think there are no error pertaining to flake8-bugbear as yet in our code. But I found it's errors reporting on code really useful.

**Comment by gaugup** [comment]
> I guess it just writes warnings but doesn't trigger failures?

No errors in our code as yet. But any future additions that has such issues dhould trigger a failure.

**Pull request merged**
