### PR TITLE
Update describeWhatIfCommonFunctionalities.ts to remove commented code

### PR DESCRIPTION
**Pull request by gaugup**
## Description

Update describeWhatIfCommonFunctionalities.ts to remove commented code

## Checklist

- [ ] I have added screenshots above for all UI changes.
- [ ] Documentation was updated if it was needed.
- [ ] New tests were added or changes were manually verified.

### CODE REVIEW

**Comment by romanlutz** [comment]
Did you check how it got there? Perhaps whoever added it meant to do something with it?

**Comment by gaugup** [comment]
> Did you check how it got there? Perhaps whoever added it meant to do something with it?

@vinuthakaranth do you know why this was commented out in PR  https://github.com/microsoft/responsible-ai-toolbox/pull/1241?

**Comment by vinuthakaranth** [comment]
> > Did you check how it got there? Perhaps whoever added it meant to do something with it?
> 
> @vinuthakaranth do you know why this was commented out in PR #1241?
discussed offline - 
I see it is commented by Bo in https://github.com/microsoft/responsible-ai-toolbox/pull/1241/files#diff-fc7fb0a99da063875dd2dd95052ab15c164ee6330e059f606de18f1fefa97e0d

looks like it has been commented to merge his PR. We have to revisit to uncomment this part of code. If we have mandatory rule of removing commented code, can you please create a task as follow up to add this code back?

**Comment by gaugup** [comment]
PR to enable sub bar tests is here:- https://github.com/microsoft/responsible-ai-toolbox/pull/1468

**Pull request closed without merging**
