### PR TITLE
Explicitly set chart background color

### PR DESCRIPTION
**Pull request by hawestra**
explicitly set highchart background color to semantic body background 

## Description
explicitly set highchart background color to semantic body background to align with fluent ui v2 upgrades 
to address this bug: [Bug 2306817](https://msdata.visualstudio.com/Vienna/_workitems/edit/2306817): [FluentV2Wave1] Tables and other UI elements in RAI dashboard have strange white/transparent color with new fluentui

See gif below in comments (file was too large). Follow up bug for the background not updating with the theme:
[Bug 2324252](https://msdata.visualstudio.com/Vienna/_workitems/edit/2324252): changing theme doesn't update background color when running locally
## Checklist

- [ ] I have added screenshots above for all UI changes.
- [ ] I have added e2e tests for all UI changes.
- [ ] Documentation was updated if it was needed.

### CODE REVIEW

**Comment by RubyZ10** [comment]
Could you please send a gif for the change with theme switching thanks!

**Review by romanlutz — APPROVED** [review]
Changes look good. Agree with Ruby on sharing a gif or screenshot 🙂

**Comment by hawestra** [comment]
themeWhite

**Comment by hawestra** [comment]
themeDark

**Review by imatiach-msft — APPROVED** [review]

**Review by RubyZ10 — APPROVED** [review]

**Pull request merged**
