### PR TITLE
Finalize ai-toolkit

### PR DESCRIPTION
**Pull request by Ninja-man07**
## Checklist

- [x] I have added screenshots above for all UI changes.
- [x] I have added e2e tests for all UI changes.
- [x] Documentation was updated if it was needed.

### CODE REVIEW

**Comment by romanlutz** [comment]
I'm assuming this is spam and closing accordingly. If I somehow misclassified it, please do let me know and we can consider it.

**Comment by Ninja-man07** [comment]
```html
I<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NAPI Website</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <!-- Navigation -->
    <nav>
        <ul>
            <li><a href="#home">Home</a></li>
            <li><a href="#github">GitHub Subdomains</a></li>
            <li><a href="#api">API Reference</a></li>
            <li><a href="#sandbox">Sandbox</a></li>
        </ul>
    </nav>

    <!-- Home Section -->
    <section id="home">
        <h1>Welcome to NAPI Website</h1>
        <!-- <!<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Head content, including title and styles -->
</head>
<body>
    <nav>
        <!-- Navigation menu links -->
    </nav>

    <!-- Week 1: Introduction to Online Entrepreneurship -->
    <section id="week1">
        <!-- Content for Week 1 -->
    </section>

    <!-- Week 2: Identifying Profitable Online Business Ideas -->
    <section id="week2">
        <!-- Content for Week 2 -->
    </section>

    <!-- Week 3: Creating a Strong Online Brand -->
    <section id="week3">
        <!-- Content for Week 3 -->
    </section>

    <!-- Week 4: Building Your Online Platform -->
    <section id="week4">
        <!-- Content for Week 4 -->
    </section>

    <!-- Week 5: E-commerce and Online Sales Strategies -->
    <section id="week5">
        <!-- Content for Week 5 -->
    </section>

    <!-- Week 6: Digital Marketing and Customer Acquisition -->
    <section id="week6">
        <!-- Content for Week 6 -->
    </section>

    <!-- Week 7: Scaling Your Online Business -->
    <section id="week7">
        <!-- Content for Week 7 -->
    </section>

    <!-- Week 8: Legal, Financial, and Future Growth -->
    <section id="week8">
        <!-- Content for Week 8 -->
    </section>

    <footer>
        <!-- Footer content -->
    </footer>

    <script src="main.js"></script>
</body>
</html>
>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NAPI Website</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <nav>
        <ul>
            <li><a href="#home">Home</a></li>
            <li><a href="#github">GitHub Subdomains</a></li>
            <li><a href="#api">API Reference</a></li>
            <li><a href="#sandbox">Sandbox</a></li>
            <li><a href="#custom-js">Customizable JavaScript</a></li>
        </ul>
    </nav>

    <section id="home">
        <h1>Welcome to NAPI Website</h1>
        <p>This is the homepage content.</p>
    </section>

    <section id="github">
        <h2>GitHub Subdomains</h2>
        <p>This section hosts your GitHub subdomains.</p>
    </section>

    <section id="api">
        <h2>API Reference</h2>
        <p>This section provides the API documentation.</p>
    </section>

    <section id="sandbox">
        <h2>Sandbox</h2>
        <p>This section includes the interactive API sandbox.</p>
    </section>

    <section id="custom-js">
        <h2>Customizable JavaScript</h2>
        <p>This section contains customizable JavaScript modules.</p>
    </section>

    <footer>
        <p>&copy; 2023 NAPI Website. All rights reserved.</p>
    </footer>

    <script src="main.js"></script>
</body>
</html>
 -->
    </section>

    <!-- GitHub Subdomains Section -->
    <section id="github">
        <h2>GitHub Subdomains</h2>
        <!-- GitHub subdomains content here -->
    </section>

    <!-- API Reference Section -->
    <section id="api">
        <h2>API Reference</h2>
        <!-- API reference content here -->
    </section>

    <!-- Sandbox Section -->
    <section id="sandbox">
        <h2>Sandbox</h2>
        <!-- Sandbox content here -->
    </section>

    <!-- Customizable JavaScript Section -->
    <section id="custom-js">
        <h2>Customizable JavaScript</h2>
        <!-- Custom JavaScript content here -->
    </section>

    <footer>
        <!-- Footer content here -->
    </footer>

    <script src="main.js"></script>
</body>
</html>
```

**Comment by Ninja-man07** [comment]
```typescript
```javascript
From d6ccef2382438998db688ba1964d8aa9f374156d Mon Sep 17 00:00:00 2001
From: Ninja-man07 <133485018+Ninja-man07@users.noreply.github.com>
Date: Tue, 27 Jun 2023 13:22:04 -0700
Subject: [PATCH 1/2] Update describeRadioButtonFeatureWeightsSelector.ts

---
 .../describeRadioButtonFeatureWeightsSelector.ts                | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts b/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts
index 16cdd54400..8efab15757 100644
--- a/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts
+++ b/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts
@@ -1,6 +1,6 @@
 // Copyright (c) Microsoft Corporation.
 // Licensed under the MIT License.
-
+[![Python Linting](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml/badge.svg?event=check_run)](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml)
 import { Locators } from "../../../util/Constants";
 import { validateBarChart } from "../../../util/validateBarChart";
 

From acc5fbcc928c3c88aba620962d5a4eccfaa766cf Mon Sep 17 00:00:00 2001
From: Ninja-man07 <133485018+Ninja-man07@users.noreply.github.com>
Date: Tue, 27 Jun 2023 13:24:45 -0700
Subject: [PATCH 2/2] Update describeRadioButtonFeatureWeightsSelector.ts

---
 .../describeRadioButtonFeatureWeightsSelector.ts            | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts b/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts
index 8efab15757..10b3e8d9fa 100644
--- a/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts
+++ b/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts
@@ -4,7 +4,7 @@
 import { Locators } from "../../../util/Constants";
 import { validateBarChart } from "../../../util/validateBarChart";
 
-function validateTextBarChart(expectedNumValues: number): void {
+function validateTextBarChart(expectedNumValues: number): void {[![Python Linting](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml/badge.svg?event=check_run)](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml)
   validateBarChart(Locators.TextExplanationChart, expectedNumValues);
 }
 
@@ -23,7 +23,7 @@ function switchRadioButtonValidateSelection(
       validateTextBarChart(expectedNumValues);
     });
 }
-
+[![Python Linting](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml/badge.svg?event=check_run)](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml)
 export function describeRadioButtonFeatureWeightsSelector(): void {
   describe("Radio button", () => {
     it("should be set to all features by default", () => {
@@ -47,7 +47,7 @@ export function describeRadioButtonFeatureWeightsSelector(): void {
       switchRadioButtonValidateSelection(
         2,
         "NEGATIVE FEATURES",
-        notSpamNegativeExpectedNumValues
+        notSpamNegativeExpectedNumValues  
       );
     });
   });
/``` diff --git a/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts b/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts
index 16cdd54400..10b3e8d9fa 100644
--- a/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts
+++ b/apps/dashboard-e2e/src/describer/interpretText/individualFeatureImportance/describeRadioButtonFeatureWeightsSelector.ts
@@ -1,10 +1,10 @@
 // Copyright (c) Microsoft Corporation.
 // Licensed under the MIT License.
-
+[![Python Linting](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml/badge.svg?event=check_run)](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml)
 import { Locators } from "../../../util/Constants";
 import { validateBarChart } from "../../../util/validateBarChart";
 
-function validateTextBarChart(expectedNumValues: number): void {
+function validateTextBarChart(expectedNumValues: number): void {[![Python Linting](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml/badge.svg?event=check_run)](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml)
   validateBarChart(Locators.TextExplanationChart, expectedNumValues);
 }
 
@@ -23,7 +23,7 @@ function switchRadioButtonValidateSelection(
       validateTextBarChart(expectedNumValues);
     });
 }
-
+[![Python Linting](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml/badge.svg?event=check_run)](https://github.com/Ninja-man07/responsible-ai-toolbox/actions/workflows/python-linting.yml)
 export function describeRadioButtonFeatureWeightsSelector(): void {
   describe("Radio button", () => {
     it("should be set to all features by default", () => {
@@ -47,7 +47,7 @@ export function describeRadioButtonFeatureWeightsSelector(): void {
       switchRadioButtonValidateSelection(
         2,
         "NEGATIVE FEATURES",
-        notSpamNegativeExpectedNumValues
+        notSpamNegativeExpectedNumValues  
       );
     });
   });
```

**Comment by Ninja-man07** [comment]
#2240 
@mtodd 
#2246
@Ninja-man07

**Pull request closed without merging**
