### PR TITLE
Add License and Requirements to Source Distribtion

### PR DESCRIPTION
**Pull request by janjagusch**
## Description

Hi!

We're currently making an effort to put the responsible-ai-toolbox on conda-forge. You can find the corresponding PRs here:

- https://github.com/conda-forge/staged-recipes/pull/19439
- https://github.com/conda-forge/staged-recipes/pull/19449
- https://github.com/conda-forge/staged-recipes/pull/19445
- https://github.com/conda-forge/staged-recipes/pull/19446
- https://github.com/conda-forge/staged-recipes/pull/19448

We've noticed that there are some files missing in the source distribution that you ship on PyPI.

- The license is missing
- The `requirements.txt` file is missing, which is read inside the `setup.py` ([example](https://github.com/microsoft/responsible-ai-toolbox/blob/0a303e6fa1fc2a08d6c29f6b7f46b536579584e2/erroranalysis/setup.py#L14-L16))

Adding the `requirements.txt` to the source distribution can be accomplished by adding a `MANIFEST.in` file to the root of the package repository. As there is no way to reference files outside the root of the repository when building a source distribution ([source](https://github.com/pypa/setuptools/issues/2339)), we had to copy the license file into all package directories. We also made sure that the `dist/` directory does not get committed to version control when testing this.

## Checklist

- [ ] I have added screenshots above for all UI changes.
- [ ] I have added e2e tests for all UI changes.
- [ ] Documentation was updated if it was needed.

### CODE REVIEW

**Review by romanlutz — APPROVED** [review]
Thanks @janjagusch ! This looks fine to me. @xuke444 @imatiach-msft ?

**Comment by romanlutz** [comment]
FWIW we'll have to override the failing CD build since the secret isn't available for people with their own forks (which is also something we should fix at some point). Since there are no real code changes I'm not worried about that, though.

**Review by imatiach-msft — APPROVED** [review]

**Comment by imatiach-msft** [comment]
@janjagusch do you need us to do another pypi release, or are you all set to add those packages to conda-forge?

**Comment by imatiach-msft** [comment]
FYI I force-merged this PR due to the CD build failing, I think this is something that we really need to resolve as soon as possible

**Comment by janjagusch** [comment]
> @janjagusch do you need us to do another pypi release, or are you all set to add those packages to conda-forge?

Thanks for merging @imatiach-msft! If you could release new versions, that would be great. I can work around the missing files, but this way to build would be much easier. Thanks a lot!

**Pull request merged**
